Issue 85
neurogears/onix-refactor pull request #111
Opened 2024-06-18 17:15 UTC by jonnew

This PR contains most functionality for HeadstageNeuropixelsV1e. It is missing shank configuration which is closely tied into GUI development on issue-106.

2024-06-19 11:34 UTC, glopesdev requested changes

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        [Description("Path to the NRIC1384 gain calibration file.")]
Is the reference to NRIC1384 correct?

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        [Description("Path to the NRIC1384 ADC calibration file.")]
Same as above

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +                if (probeMetadata.ProbeSerialNumber == null)
This seems to be a `ulong` property so it cannot be null, was this intended to be a nullable property, or is this case never supposed to happen?

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        x50 = 0b000,
Would you consider renaming these to `Gain50`, `Gain125`, etc for consistency with C# naming conventions?

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
> +            public double? PortVoltage { get; set; } = null;
This could now be removed by taking advantage of the changes in #105.

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
> +                if (PortVoltage == null)
Same here, this check could be removed, since this function is only ever called if there is no port voltage override.

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                throw new ArgumentException("Calibraiton files must be specified.");
```suggestion
                throw new ArgumentException("Calibration files must be specified.");
```

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                throw new ArgumentException("Calibraiton file serial numbers do not match.");
```suggestion
                throw new ArgumentException("Calibration file serial numbers do not match.");
```

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                    // to droop and mess up internal state. Or that MCLK is just not good enough to
```suggestion
                    // to drop and mess up internal state. Or that MCLK is just not good enough to
```

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                    throw new WorkflowException($"Shift register {srAddress} status check failed.");
```suggestion
                    throw new InvalidOperationException($"Shift register {srAddress} status check failed.");
```

2024-06-19 11:34 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixesV1eDeviceInfo.cs
> +    class NeuropixesV1eDeviceInfo : DeviceInfo
```suggestion
    class NeuropixelsV1eDeviceInfo : DeviceInfo
```

Probably easiest to rename the whole file to fix this typo.

2024-06-19 14:49 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        [Description("Path to the NRIC1384 gain calibration file.")]
No, should be Neuropixel 1.0

2024-06-19 15:03 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +                if (probeMetadata.ProbeSerialNumber == null)
This check is not useful and should be removed. However, we are missing an important check. `probeMetadata.ProbeSerialNumber` should be passed into the constructor for `NeuropixelsV1eRegisterContext` so that a three-way serial number check can be performed. The serial number from the probe must match that of the ADC calibration file and that of the Gain calibration file. Currently, the only check is between the serial numbers in the files, but not with the actual probe.

2024-06-19 15:03 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        x50 = 0b000,
Sure, sounds good.

2024-06-19 15:04 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
> +            public double? PortVoltage { get; set; } = null;
Should with merge with main and then bring main into 105 to do this?

2024-06-19 15:04 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
> +                if (PortVoltage == null)
Cool.

2024-06-19 15:06 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                    // to droop and mess up internal state. Or that MCLK is just not good enough to
Wierdly, we actually tested this hypothesis with a clock buffer at OEPS and it did not resolve the problem. We officially have no clue how we got the FPGA based headstage to work and this not to. There is no difference we can find. 

This hack seems very reliable though so I think we can leave it alone.

2024-06-19 15:31 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
> +            public double? PortVoltage { get; set; } = null;
I have already rebased the branch to main, so it should be enough to just change the code directly now.

2024-06-19 17:12 UTC, jonnew commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
> +                    // to droop and mess up internal state. Or that MCLK is just not good enough to
droop was correct, though.

2024-06-25 14:50 UTC, glopesdev requested changes

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +            }
Agree this should follow same logic as `NeuropixelsV2eMetadata`.

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        // public const int HeadstageEEPROMAddress = 0x51;
Is this used anywhere?

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eMetadata.cs
> +            var flexI2C = new I2CRegisterContext(serializer, NeuropixelsV2e.FlexEEPROMAddress);
```suggestion
            var flexI2C = new I2CRegisterContext(serializer, NeuropixelsV1e.FlexEEPROMAddress);
```

Assumimg this should be using a reference to the V1 constants rather than V2?

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +        Ext = 0b001,
```suggestion
        External = 0b001,
```

Maybe rename to `External` for readability and consistency with the V2 definitions?

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +    public enum NeuropixelsV1CalibrationRegisterValues : uint
Consider making these internal so it doesn't show up in high-level docs and API.

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +    public enum NeuropixelsV1RecordRegisterValues : uint
Same as above

2024-06-25 14:50 UTC, glopesdev commented on OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
> +    public enum NeuropixelsV1OperationRegisterValues : uint
Same as above

2024-06-25 16:06 UTC, glopesdev approved these changes

2024-06-25 16:06 UTC, merged